# Generated by Django 6.0 on 2025-12-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('last_row', models.PositiveIntegerField(default=0)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
    ]
