# Generated by Django 6.0 on 2025-12-22 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_csvschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvschedule',
            name='oauthModal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='CsvSchedule', to='ticket.oauthmodel'),
            preserve_default=False,
        ),
    ]
